data_location: YOUR_DATA_STORE
model_yaml: "https://raw.githubusercontent.com/john-adeojo/Credit-Card-Fraud-Model-Registry/main/model%20yaml%20files/model_1a.yaml"
output_dir: "../data/06_models"
model_options:
  seed: 42
  test_size: 0.2